services:
  deb:
    image: node:20-bullseye
    restart: unless-stopped
    volumes:
      - ./data:/data
    command: tail -f /dev/null

# sudo docker exec -it turbo-svelte-example-deb-1 bash
